# Add 'test' label to any change to *.spec.js files within the source dir
test:
    - src/**/*.spec.ts
    - e2e/*

# Add 'workflows' label to any new or updated GitHub action workflow
workflows:
    - .github/workflows/*

# Add 'actions' label to any new or updated GitHub action workflow
actions:
    - .github/actions/*

# Add 'angular' label to any changes done to the React application
angular:
    - src/*

# Add 'angular' label to any changes done to the React application
ngrx:
    - src/app/root-store/*

# Add the 'documentation' label to any changes in either of the documented files
documentation:
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
