name: Bug Report
description: Report broken or incorrect behavior
labels: ["unconfirmed bug"]
body:
  - type: input
    attributes:
      label: Summary
      description: A simple summary of your bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What you did to make it happen.
         For example:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: >
        What actually happened?
    validations:
      required: true
  - type: input
    attributes:
      label: Error Message
      description: >
        If there was an error message, please paste it here.
    validations:
      required: true
  - type: input
    attributes:
      label: Screenshot
      description: >
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    attributes:
      label: Environment
      description: >
        If you are using a desktop or smartphone environment, please specify which one.

        - OS: [e.g Windows or iOS]
        - Browser: [e.g Chrome, Firefox, etc]
        - Version: [e.g 22, Latest]
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure you've properly done due diligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
