name: Deploy

on:
  schedule:
    - cron: "0 17 * * 5"

jobs:
  deploy:
    name: Deploy Chapter Website
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          echo 'Running Setup...'
          yarn
          npm install -g @angular/cli

      - name: Building Production Environment
        run: |
          echo 'Building and Compiling...'
          rm -rf dist
          yarn build
          echo ${{ secrets. ACCESS_TOKEN }}

      - name: Angular Deploy gh-pages Actions
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
          COMMIT_MESSAGE: Release ${{ github.event.pull_request.head.ref }}
          BRANCH: gh-pages # The branch the action should deploy to.
          BASE_BRANCH: master
          FOLDER: dist

      - name: Tag Deployment
        run: |
          echo 'Tagging Deployment...'
          git tag -l ${{ github.event.pull_request.head.ref }}
