name: Deploy and Update Release Notes

on:
  push:
    branches:
      - master # Successful Merge on master branch

jobs:
  deploy:
    name: Deploy Angular Application
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          echo 'Running Setup...'
          yarn install
          npm install -g @angular/cli  

      - name: Building Production Environment
        run: |
          echo 'Building and Compiling...'
          rm -rf dist
          yarn build

      - name: Angular Deploy gh-pages Actions
        uses: JamesIves/github-pages-deploy-action@releases/v2
        with:
          ACCESS_TOKEN: ${{ secrets.GREN_GITHUB_TOKEN }} # see the Configuration section for how you can create secrets
          COMMIT_MESSAGE: Release ${{ github.event.title }}
          BRANCH: gh-pages # The branch the action should deploy to.
          BASE_BRANCH: master
          FOLDER: dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

      - name: Tag Deployment
        run: |
          echo 'Tagging Deployment...'
          git tag -l ${{ github.event.title }}

  release:
    name: Update Release notes and Changelog
    runs-on: ${{ matrix.os }}
    needs: deploy

    strategy:
        matrix:
            node-version: [12.x]
            os: [ubuntu-latest]
    
    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          echo 'Running Setup...'
          yarn install

      - name: Update Release notes
        run: |
          echo 'Update Release Notes...'
          npm run gren:release -- --token=${{ secrets.GREN_GITHUB_TOKEN }}

      - name: Update Release notes
        run: |
          echo 'Update Changelog...'
          npm run gren:release -- --token=${{ secrets.GREN_GITHUB_TOKEN }}
