name: Deploy and Update Release Notes

on:
  pull_request:
    branches:
      - master # Pull requests on master branch

jobs:
  deploy:
    name: Deploy Angular Application
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v2

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          echo 'Running Setup...'
          yarn install

      - name: Deploy Changes
        run: |
          echo 'Deploy Angular Application...'
          yarn deploy --message=${{ github.event.title }}

      - name: Tag Deployment
        run: |
          echo 'Tagging Deployment...'
          git tag -l ${{ github.event.title }}

  release:
    name: Update Release notes and Changelog
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            node-version: [12.x]
            os: [ubuntu-latest]
    
    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v2

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
            echo 'Running Setup...'
            yarn install

      - name: Update Release notes
        with:
          repo-token: ${{ secrets.GREN_GITHUB_TOKEN }}
        run: |
            echo 'Update Release Notes...'
            yarn gren:release

      - name: Update Release notes
        with:  
          repo-token: ${{ secrets.GREN_GITHUB_TOKEN }}
        run: |
            echo 'Update Changelog...'
            yarn gren:release
